<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class LeaveTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();
        
        $leaveTypes = [
            [
                'code' => 'annual',
                'name' => 'Yıllık İzin',
                'description' => 'Yasal yıllık ücretli izin hakkı',
                'color_code' => '#10B981',
                'icon' => 'calendar-days',
                'is_paid' => true,
                'affects_annual_balance' => true,
                'requires_approval' => true,
                'requires_document' => false,
                'can_be_split' => true,
                'max_consecutive_days' => null,
                'max_total_days_per_year' => null,
                'min_advance_notice_days' => 30,
                'max_advance_request_days' => 365,
                'only_workdays' => true,
                'includes_weekends' => false,
                'includes_holidays' => false,
                'min_tenure_months' => 12,
                'auto_approve_conditions' => false,
                'create_timesheet_entry' => true,
                'notify_manager' => true,
                'notify_hr' => false,
                'include_in_reports' => true,
                'affects_attendance_percentage' => false,
                'legal_reference' => 'İş Kanunu Madde 53',
                'is_mandatory' => false,
                'sort_order' => 1
            ],
            [
                'code' => 'sick',
                'name' => 'Hastalık İzni',
                'description' => 'Sağlık raporu ile alınan hastalık izni',
                'color_code' => '#EF4444',
                'icon' => 'heart',
                'is_paid' => true,
                'affects_annual_balance' => false,
                'requires_approval' => true,
                'requires_document' => true,
                'can_be_split' => false,
                'max_consecutive_days' => null,
                'max_total_days_per_year' => null,
                'min_advance_notice_days' => 0,
                'max_advance_request_days' => 7,
                'only_workdays' => true,
                'includes_weekends' => false,
                'includes_holidays' => false,
                'auto_approve_conditions' => false,
                'create_timesheet_entry' => true,
                'notify_manager' => true,
                'notify_hr' => true,
                'include_in_reports' => true,
                'affects_attendance_percentage' => false,
                'legal_reference' => 'Sosyal Sigortalar Kanunu',
                'is_mandatory' => false,
                'sort_order' => 2
            ],
            [
                'code' => 'maternity',
                'name' => 'Doğum İzni',
                'description' => 'Kadın çalışanlar için doğum izni',
                'color_code' => '#F59E0B',
                'icon' => 'heart',
                'is_paid' => true,
                'affects_annual_balance' => false,
                'requires_approval' => true,
                'requires_document' => true,
                'can_be_split' => true,
                'max_consecutive_days' => 112, // 16 hafta
                'max_total_days_per_year' => 112,
                'min_advance_notice_days' => 30,
                'max_advance_request_days' => 120,
                'only_workdays' => false,
                'includes_weekends' => true,
                'includes_holidays' => true,
                'gender_restriction' => 'female',
                'auto_approve_conditions' => false,
                'create_timesheet_entry' => true,
                'notify_manager' => true,
                'notify_hr' => true,
                'include_in_reports' => true,
                'affects_attendance_percentage' => false,
                'legal_reference' => 'İş Kanunu Madde 74',
                'is_mandatory' => true,
                'sort_order' => 3
            ],
            [
                'code' => 'paternity',
                'name' => 'Babalık İzni',
                'description' => 'Erkek çalışanlar için babalık izni',
                'color_code' => '#3B82F6',
                'icon' => 'user',
                'is_paid' => true,
                'affects_annual_balance' => false,
                'requires_approval' => true,
                'requires_document' => true,
                'can_be_split' => false,
                'max_consecutive_days' => 5,
                'max_total_days_per_year' => 5,
                'min_advance_notice_days' => 7,
                'max_advance_request_days' => 60,
                'only_workdays' => true,
                'includes_weekends' => false,
                'includes_holidays' => false,
                'gender_restriction' => 'male',
                'auto_approve_conditions' => false,
                'create_timesheet_entry' => true,
                'notify_manager' => true,
                'notify_hr' => true,
                'include_in_reports' => true,
                'affects_attendance_percentage' => false,
                'legal_reference' => 'İş Kanunu Madde 74',
                'is_mandatory' => false,
                'sort_order' => 4
            ],
            [
                'code' => 'marriage',
                'name' => 'Evlilik İzni',
                'description' => 'Evlilik için verilen izin',
                'color_code' => '#EC4899',
                'icon' => 'heart',
                'is_paid' => true,
                'affects_annual_balance' => false,
                'requires_approval' => true,
                'requires_document' => true,
                'can_be_split' => false,
                'max_consecutive_days' => 3,
                'max_total_days_per_year' => 3,
                'min_advance_notice_days' => 15,
                'max_advance_request_days' => 90,
                'only_workdays' => true,
                'includes_weekends' => false,
                'includes_holidays' => false,
                'max_occurrences_per_year' => 1,
                'auto_approve_conditions' => false,
                'create_timesheet_entry' => true,
                'notify_manager' => true,
                'notify_hr' => false,
                'include_in_reports' => true,
                'affects_attendance_percentage' => false,
                'legal_reference' => 'Toplu İş Sözleşmesi',
                'is_mandatory' => false,
                'sort_order' => 5
            ],
            [
                'code' => 'funeral',
                'name' => 'Cenaze İzni',
                'description' => 'Yakın akraba vefatı için cenaze izni',
                'color_code' => '#6B7280',
                'icon' => 'user-minus',
                'is_paid' => true,
                'affects_annual_balance' => false,
                'requires_approval' => true,
                'requires_document' => false,
                'can_be_split' => false,
                'max_consecutive_days' => 3,
                'max_total_days_per_year' => 9,
                'min_advance_notice_days' => 0,
                'max_advance_request_days' => 7,
                'only_workdays' => true,
                'includes_weekends' => false,
                'includes_holidays' => false,
                'max_occurrences_per_year' => 3,
                'auto_approve_conditions' => true,
                'auto_approve_rules' => json_encode(['immediate_family' => true]),
                'create_timesheet_entry' => true,
                'notify_manager' => true,
                'notify_hr' => false,
                'include_in_reports' => true,
                'affects_attendance_percentage' => false,
                'legal_reference' => 'Toplu İş Sözleşmesi',
                'is_mandatory' => false,
                'sort_order' => 6
            ],
            [
                'code' => 'excuse',
                'name' => 'Mazeret İzni',
                'description' => 'Kısa süreli mazeret izinleri',
                'color_code' => '#8B5CF6',
                'icon' => 'clock',
                'is_paid' => true,
                'affects_annual_balance' => false,
                'requires_approval' => true,
                'requires_document' => false,
                'can_be_split' => true,
                'max_consecutive_days' => 1,
                'max_total_days_per_year' => 6,
                'min_advance_notice_days' => 1,
                'max_advance_request_days' => 30,
                'only_workdays' => true,
                'includes_weekends' => false,
                'includes_holidays' => false,
                'auto_approve_conditions' => false,
                'create_timesheet_entry' => true,
                'notify_manager' => true,
                'notify_hr' => false,
                'include_in_reports' => true,
                'affects_attendance_percentage' => false,
                'legal_reference' => 'Şirket Politikası',
                'is_mandatory' => false,
                'sort_order' => 7
            ],
            [
                'code' => 'unpaid',
                'name' => 'Ücretsiz İzin',
                'description' => 'Maaş kesintisi ile alınan izin',
                'color_code' => '#64748B',
                'icon' => 'minus-circle',
                'is_paid' => false,
                'affects_annual_balance' => false,
                'requires_approval' => true,
                'requires_document' => false,
                'can_be_split' => true,
                'max_consecutive_days' => 30,
                'max_total_days_per_year' => 90,
                'min_advance_notice_days' => 15,
                'max_advance_request_days' => 180,
                'only_workdays' => true,
                'includes_weekends' => false,
                'includes_holidays' => false,
                'auto_approve_conditions' => false,
                'create_timesheet_entry' => true,
                'notify_manager' => true,
                'notify_hr' => true,
                'include_in_reports' => true,
                'affects_attendance_percentage' => true,
                'legal_reference' => 'İş Kanunu Madde 40',
                'is_mandatory' => false,
                'sort_order' => 8
            ]
        ];
        
        foreach ($leaveTypes as $leaveType) {
            DB::table('leave_types')->insert(array_merge($leaveType, [
                'created_at' => $now,
                'updated_at' => $now
            ]));
        }
    }
}