<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Subcontractor;
use App\Models\SubcontractorCategory;

class SubcontractorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Kategorileri al (zaten varsa yeniden oluşturma)
        $categories = SubcontractorCategory::all()->keyBy('code');

        // Eğer kategoriler yoksa, önce oluştur
        if ($categories->isEmpty()) {
            $this->call(SubcontractorCategorySeeder::class);
            $categories = SubcontractorCategory::all()->keyBy('code');
        }

        $subcontractors = [
            [
                'company_name' => 'Yıldırım Elektrik İnşaat San. ve Tic. Ltd. Şti.',
                'category_code' => 'ELEKTRIK',
                'tax_number' => '1234567890',
                'tax_office' => 'Kadıköy',
                'authorized_person' => 'Mehmet Yıldırım',
                'authorized_title' => 'Genel Müdür',
                'authorized_phone' => '0216 555 0101',
                'authorized_email' => 'mehmet@yildirim-elektrik.com',
                'phone' => '0216 555 0100',
                'email' => 'info@yildirim-elektrik.com',
                'address' => 'Fenerbahçe Mah. Elektrik Sok. No:15 Kadıköy/İSTANBUL',
                'city' => 'İstanbul',
                'district' => 'Kadıköy',
                'status' => 'active',
                'is_approved' => true,
                'notes' => 'Güvenilir firma, 15 yıllık tecrübe. Elektrik tesisatı, pano montajı, aydınlatma sistemleri.',
                'rating' => 4.5,
                'completed_projects' => 15,
            ],
            [
                'company_name' => 'Öztürk Tesisat Mühendislik A.Ş.',
                'category_code' => 'MEKANIK',
                'tax_number' => '9876543210',
                'tax_office' => 'Beşiktaş',
                'authorized_person' => 'Ali Öztürk',
                'authorized_title' => 'Yönetim Kurulu Başkanı',
                'authorized_phone' => '0212 555 0202',
                'authorized_email' => 'ali@ozturk-tesisat.com.tr',
                'phone' => '0212 555 0200',
                'email' => 'iletisim@ozturk-tesisat.com.tr',
                'address' => 'Levent Mah. Tesisat Cad. No:42 Beşiktaş/İSTANBUL',
                'city' => 'İstanbul',
                'district' => 'Beşiktaş',
                'status' => 'active',
                'is_approved' => true,
                'notes' => 'Zamanında teslim, kaliteli iş. Sıhhi tesisat, ısıtma sistemleri, klima montajı.',
                'rating' => 4.8,
                'completed_projects' => 23,
            ],
            [
                'company_name' => 'Demir Çelik Konstrüksiyon Ltd. Şti.',
                'category_code' => 'DEMIR',
                'tax_number' => '5555666677',
                'tax_office' => 'Kartal',
                'authorized_person' => 'Hasan Demir',
                'authorized_title' => 'Ortağı',
                'authorized_phone' => '0216 555 0303',
                'authorized_email' => 'hasan@demircelik.com',
                'phone' => '0216 555 0300',
                'email' => 'info@demircelik.com',
                'address' => 'Organize Sanayi Bölgesi 3. Cad. No:28 Kartal/İSTANBUL',
                'city' => 'İstanbul',
                'district' => 'Kartal',
                'status' => 'active',
                'is_approved' => true,
                'notes' => 'Ağır metal işlerinde uzman. Çelik konstrüksiyon, demir doğrama.',
                'rating' => 4.3,
                'completed_projects' => 18,
            ],
            [
                'company_name' => 'Anadolu Boya ve Badana Hizmetleri',
                'category_code' => 'BOYA',
                'tax_number' => '3333444455',
                'tax_office' => 'Ümraniye',
                'authorized_person' => 'Mustafa Kaya',
                'authorized_title' => 'İşletme Sahibi',
                'authorized_phone' => '0216 555 0404',
                'authorized_email' => 'mustafa@anadoluboya.com',
                'phone' => '0216 555 0400',
                'email' => 'info@anadoluboya.com',
                'address' => 'Çakmak Mah. Boya Sok. No:8 Ümraniye/İSTANBUL',
                'city' => 'İstanbul',
                'district' => 'Ümraniye',
                'status' => 'active',
                'is_approved' => true,
                'notes' => 'İç boya, dış cephe boyası, dekoratif boya.',
                'rating' => 4.0,
                'completed_projects' => 32,
            ],
            [
                'company_name' => 'Marmara Seramik Kaplama İnşaat',
                'category_code' => 'SERAMIK',
                'tax_number' => '7777888899',
                'tax_office' => 'Maltepe',
                'authorized_person' => 'Ahmet Yılmaz',
                'authorized_title' => 'Proje Müdürü',
                'authorized_phone' => '0216 555 0505',
                'authorized_email' => 'ahmet@marmaraseramik.com',
                'phone' => '0216 555 0500',
                'email' => 'info@marmaraseramik.com',
                'address' => 'Cevizli Mah. Seramik Cad. No:12 Maltepe/İSTANBUL',
                'city' => 'İstanbul',
                'district' => 'Maltepe',
                'status' => 'active',
                'is_approved' => true,
                'notes' => 'Özel kesim ve uygulama konusunda deneyimli. Seramik, fayans, granit.',
                'rating' => 4.6,
                'completed_projects' => 27,
            ],
            [
                'company_name' => 'Güneş Alüminyum Doğrama San. Tic.',
                'category_code' => 'DOGRAMA',
                'tax_number' => '2222333344',
                'tax_office' => 'Pendik',
                'authorized_person' => 'Cemil Güneş',
                'authorized_title' => 'Genel Müdür',
                'authorized_phone' => '0216 555 0606',
                'authorized_email' => 'cemil@gunesaluminyum.com',
                'phone' => '0216 555 0600',
                'email' => 'info@gunesaluminyum.com',
                'address' => 'Kurtköy Sanayi Sitesi B Blok No:45 Pendik/İSTANBUL',
                'city' => 'İstanbul',
                'district' => 'Pendik',
                'status' => 'active',
                'is_approved' => true,
                'notes' => 'Alüminyum doğrama, PVC pencere, otomatik kapı.',
                'rating' => 4.4,
                'completed_projects' => 20,
            ],
            [
                'company_name' => 'Mega Betonarme Yapı A.Ş.',
                'category_code' => 'BETONARME',
                'tax_number' => '6666777788',
                'tax_office' => 'Esenyurt',
                'authorized_person' => 'İbrahim Çelik',
                'authorized_title' => 'İnşaat Müdürü',
                'authorized_phone' => '0212 555 0707',
                'authorized_email' => 'ibrahim@megabeton.com.tr',
                'phone' => '0212 555 0700',
                'email' => 'info@megabeton.com.tr',
                'address' => 'Kıraç Mah. Beton Cad. No:100 Esenyurt/İSTANBUL',
                'city' => 'İstanbul',
                'district' => 'Esenyurt',
                'status' => 'active',
                'is_approved' => true,
                'notes' => 'Büyük ölçekli projeler yapabilir. Beton dökümü, kalıp işleri.',
                'rating' => 4.7,
                'completed_projects' => 12,
            ],
            [
                'company_name' => 'Aykut İzolasyon Sistemleri Ltd.',
                'category_code' => 'IZOLASYON',
                'tax_number' => '4444555566',
                'tax_office' => 'Sarıyer',
                'authorized_person' => 'Aykut Arslan',
                'authorized_title' => 'Teknik Sorumlu',
                'authorized_phone' => '0212 555 0808',
                'authorized_email' => 'aykut@aykutizolasyon.com',
                'phone' => '0212 555 0800',
                'email' => 'info@aykutizolasyon.com',
                'address' => 'Maslak Mah. İzolasyon Sok. No:7 Sarıyer/İSTANBUL',
                'city' => 'İstanbul',
                'district' => 'Sarıyer',
                'status' => 'active',
                'is_approved' => true,
                'notes' => 'Su yalıtımı, ısı yalıtımı, ses yalıtımı uzmanı.',
                'rating' => 4.5,
                'completed_projects' => 30,
            ],
            [
                'company_name' => 'Çatı Ustası İnşaat Taah. Ltd.',
                'category_code' => 'CATI',
                'tax_number' => '8888999900',
                'tax_office' => 'Şişli',
                'authorized_person' => 'Serkan Kılıç',
                'authorized_title' => 'Usta Başı',
                'authorized_phone' => '0212 555 0909',
                'authorized_email' => 'serkan@catiustasi.com',
                'phone' => '0212 555 0900',
                'email' => 'info@catiustasi.com',
                'address' => 'Mecidiyeköy Mah. Çatı Cad. No:34 Şişli/İSTANBUL',
                'city' => 'İstanbul',
                'district' => 'Şişli',
                'status' => 'active',
                'is_approved' => true,
                'notes' => 'Hızlı çözüm üretir. Çatı örtüsü, izolasyon.',
                'rating' => 4.2,
                'completed_projects' => 25,
            ],
            [
                'company_name' => 'Yeşil Vadi Peyzaj Ltd. Şti.',
                'category_code' => 'PEYZAJ',
                'tax_number' => '1111222233',
                'tax_office' => 'Büyükçekmece',
                'authorized_person' => 'Zeynep Yeşil',
                'authorized_title' => 'Peyzaj Mimarı',
                'authorized_phone' => '0212 555 1010',
                'authorized_email' => 'zeynep@yesilvadipeyzaj.com',
                'phone' => '0212 555 1000',
                'email' => 'info@yesilvadipeyzaj.com',
                'address' => 'Mimarsinan Mah. Yeşil Vadi Sok. No:5 Büyükçekmece/İSTANBUL',
                'city' => 'İstanbul',
                'district' => 'Büyükçekmece',
                'status' => 'active',
                'is_approved' => true,
                'notes' => 'Bahçe düzenleme, sulama sistemleri uzmanı.',
                'rating' => 4.9,
                'completed_projects' => 40,
            ],
            // Pending approval examples
            [
                'company_name' => 'Aslan Yapı İnşaat Taah.',
                'category_code' => 'ALCI_SIVA',
                'tax_number' => '9999000011',
                'tax_office' => 'Bakırköy',
                'authorized_person' => 'Burak Aslan',
                'authorized_title' => 'Şantiye Şefi',
                'authorized_phone' => '0212 555 1111',
                'authorized_email' => 'burak@aslanyapi.com',
                'phone' => '0212 555 1100',
                'email' => 'info@aslanyapi.com',
                'address' => 'Ataköy Mah. Sıva Sok. No:22 Bakırköy/İSTANBUL',
                'city' => 'İstanbul',
                'district' => 'Bakırköy',
                'status' => 'active',
                'is_approved' => false,
                'notes' => 'Belge kontrolü bekleniyor. Alçı işleri, sıva, mantolama.',
                'rating' => 0,
                'completed_projects' => 0,
            ],
            [
                'company_name' => 'Teknik Havalandırma Sistemleri',
                'category_code' => 'HAVALANDIRMA',
                'tax_number' => '0000111122',
                'tax_office' => 'Ataşehir',
                'authorized_person' => 'Can Tekin',
                'authorized_title' => 'Mühendis',
                'authorized_phone' => '0216 555 1212',
                'authorized_email' => 'can@teknikhavalandirma.com',
                'phone' => '0216 555 1200',
                'email' => 'info@teknikhavalandirma.com',
                'address' => 'İçerenköy Mah. Havalandırma Cad. No:67 Ataşehir/İSTANBUL',
                'city' => 'İstanbul',
                'district' => 'Ataşehir',
                'status' => 'active',
                'is_approved' => false,
                'notes' => 'Referans kontrolü yapılacak.',
                'rating' => 0,
                'completed_projects' => 0,
            ],
        ];

        foreach ($subcontractors as $data) {
            $categoryCode = $data['category_code'];
            unset($data['category_code']);

            $category = $categories->get($categoryCode);
            if ($category) {
                $data['category_id'] = $category->id;
            }

            Subcontractor::create($data);
        }
    }
}